//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSocial
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlobPost
    {
        public int imageId { get; set; }
        public Nullable<int> imageIdPost { get; set; }
        public byte[] blob { get; set; }
        public string imageType { get; set; }
        public string imageSize { get; set; }
        public string imageName { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
